# Generated by Django 5.1 on 2024-08-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='photos_buy_to_sell')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(default='admin', max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
    ]
