# Generated by Django 5.1 on 2024-08-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_to_sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos_buy_to_sell/%Y/%m/%d'),
        ),
    ]
