# Generated by Django 5.1 on 2024-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_to_sell', '0002_poster_price_alter_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos_buy_to_sell/%Y/%m'),
        ),
    ]
