# Generated by Django 5.1 on 2024-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy_to_sell', '0003_alter_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='miniature',
            field=models.ImageField(blank=True, upload_to='miniature_photos_buy_to_sell/%Y/%m'),
        ),
    ]
